### ISSUE TITLE
Configure CI for automated testing on pull requests

### ISSUE THREAD

**Issue by Neilos** [Mentessi/toastmasters#27]
(CI = Continuous Integration)
It is most frequently used to run automated deployments and automated testing.
bluespot usually only uses CI for testing ('cos Heroku deployments are so simple)

Having tests run automatically on Circle CI makes approving pull requests better, as the reviewer can see that all the tests pass before approving. It can also become part of your development workflow when running tests takes a long time - just push to Github and get Circle to run your tests while you keep developing locally.

Lot's of CI options but we usually use CircleCI with Github.
[CircleCI](https://circleci.com/docs/2.0/hello-world/)
For an example of circle CI configuration see Cadence repo in bluespot Github.

(With paid pipelines, you can now run CI on [Heroku](https://devcenter.heroku.com/articles/heroku-ci), but I've never used that.)

**Comment by Mentessi** [comment]
Done!
